name: Build JiosaavnAPI Docker Image
on:
  push:
    branches: [ main ]
    paths:
      - jiosaavnapi/**
  pull_request:
    branches: [ main ]
    paths:
      - jiosaavnapi/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: Docker Build Niko Music
        run: |
         docker build ./jiosaavnapi -t zingytomato/jiosaavnapi:latest 
      - name: Push to Docker Hub
        run: |
          docker push zingytomato/jiosaavnapi:latest 
